// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ItsApe.ArtifactDetector.Utilities.NativeMethods.TaskBarButton.fsStyle")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:ItsApe.ArtifactDetector.Utilities.NativeMethods.TaskBarButton.fsState")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId = "8", Scope = "member", Target = "ItsApe.ArtifactDetector.Utilities.NativeMethods.#CreateProcessAsUserW(System.IntPtr,System.String,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,System.Boolean,System.UInt32,System.IntPtr,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+Startupinfo&,ItsApe.ArtifactDetector.Utilities.NativeMethods+ProcessInformation&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId = "2", Scope = "member", Target = "ItsApe.ArtifactDetector.Utilities.NativeMethods.#CreateProcessAsUserW(System.IntPtr,System.String,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,System.Boolean,System.UInt32,System.IntPtr,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+Startupinfo&,ItsApe.ArtifactDetector.Utilities.NativeMethods+ProcessInformation&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA2101:SpecifyMarshalingForPInvokeStringArguments", MessageId = "1", Scope = "member", Target = "ItsApe.ArtifactDetector.Utilities.NativeMethods.#CreateProcessAsUserW(System.IntPtr,System.String,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,ItsApe.ArtifactDetector.Utilities.NativeMethods+SecurityAttributes&,System.Boolean,System.UInt32,System.IntPtr,System.String,ItsApe.ArtifactDetector.Utilities.NativeMethods+Startupinfo&,ItsApe.ArtifactDetector.Utilities.NativeMethods+ProcessInformation&)")]

